modules/api/controllers/CurrencyController.php
<?php

namespace app\modules\api\controllers;

use app\models\db\Currency;
use app\models\db\Rate;
use yii\base\DynamicModel;
use yii\filters\auth\HttpBearerAuth;
use yii\filters\ContentNegotiator;
use yii\filters\RateLimiter;
use yii\filters\VerbFilter;
use yii\rest\Controller;
use yii\web\Response;

/**
 * Class CurrencyController
 * @package app\modules\api\controllers
 */
class CurrencyController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'contentNegotiator' => [
                'class' => ContentNegotiator::class,
                'formats' => [
                    'application/json' => Response::FORMAT_JSON,
                    'application/xml' => Response::FORMAT_XML,
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'index' => ['GET'],
                    'view' => ['GET'],
                ],
            ],
            'authenticator' => [
                'class' => HttpBearerAuth::class,
            ],
            'rateLimiter' => [
                'class' => RateLimiter::class,
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'index' => [
                'class' => 'app\modules\api\actions\IndexAction',
                'modelClass' => Currency::class
            ],
            'view' => [
                'class' => 'yii\rest\ViewAction',
                'modelClass' => Currency::class
            ],
            'rates' => [
                'class' => 'app\modules\api\actions\IndexAction',
                'modelClass' => Rate::class,
                'dataFilter' => [
                    'class' => 'yii\data\DataFilter',
                    'filterAttributeName' => 'filter',
                    'searchModel' =>  function () {
                        return (new DynamicModel(['currency_id']))->addRule('currency_id', 'integer');
                    },
                ]
            ],
        ];
    }
}

modules/api/controllers/DefaultController.php
<?php

namespace app\modules\api\controllers;

use yii\filters\AccessControl;
use yii\web\Controller;

/**
 * Class DefaultController
 * @package app\modules\api\controllers
 */
class DefaultController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * @return string
     */
    public function actionIndex()
    {
        $this->view->title = 'API';

        $this->view->params['breadcrumbs'][] = $this->view->title;

        return $this->render('index');
    }
}

modules/api/views/default/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

?>
<div class="api-index">
    <h1 class="no-margin clearfix">
        <?= Html::encode($this->title)?>
    </h1>
    <hr>
    <p>Для доступа к API используйте указанные данные и ссылки</p>
    <dl class="dl-horizontal">
        <dt>Bearer токен:</dt>
        <dd><?=Yii::$app->user->identity->token?></dd>
        <dt>Все курсы валют:</dt>
        <dd>
            <a href="<?= Url::toRoute(['currency/index'])?>">
                <?=Yii::$app->urlManager->createAbsoluteUrl('/api/currency/index')?>
            </a>
        </dd>
        <dt>Один курс валюты:</dt>
        <dd>
            <a href="<?= Url::to(['currency/view', 'id' => 0])?>">
                <?=Yii::$app->urlManager->createAbsoluteUrl(['/api/currency/view', 'id' => 0])?>
            </a>
        </dd>
        <dt>История курсов:</dt>
        <dd>
            <a href="<?= Url::to(['currency/rates'])?>">
                <?=Yii::$app->urlManager->createAbsoluteUrl(['/api/currency/rates'])?>
            </a>
        </dd>
    </dl>
</div>